{"name": "При создании заказа счетчик \"За сегодня\" увлеичивается", "status": "passed", "steps": [{"name": "Клик на \"Лента заказов\"", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <a class=\"AppHeader_header__link__3D_hX\" href=\"/feed\">...</a> is not clickable at point (284, 28). Other element would receive the click: <path d=\"M29.425 29H21.361C20.4223 29 19.745 28.7867 19.329 28.36C19.0623 28.0827 18.8863 27.768 18.801 27.416C18.737 27.1813 18.705 26.8187 18.705 26.328V22.2H17.105V20.104H18.705V16.552H21.377V20.104H29.425V22.2H21.377V25.672C21.377 26.1627 21.489 26.4987 21.713 26.68C21.8943 26.8293 22.1983 26.904 22.625 26.904H29.425V29Z\" fill=\"white\"></path>\n  (Session info: chrome=129.0.6668.91)\nStacktrace:\n#0 0x5a6ab89abf8a <unknown>\n#1 0x5a6ab86925e0 <unknown>\n#2 0x5a6ab86e8866 <unknown>\n#3 0x5a6ab86e678d <unknown>\n#4 0x5a6ab86e4237 <unknown>\n#5 0x5a6ab86e3646 <unknown>\n#6 0x5a6ab86d6a98 <unknown>\n#7 0x5a6ab8706b22 <unknown>\n#8 0x5a6ab86d6478 <unknown>\n#9 0x5a6ab8706cee <unknown>\n#10 0x5a6ab8725d7d <unknown>\n#11 0x5a6ab87068c3 <unknown>\n#12 0x5a6ab86d46b3 <unknown>\n#13 0x5a6ab86d568e <unknown>\n#14 0x5a6ab897698b <unknown>\n#15 0x5a6ab897a911 <unknown>\n#16 0x5a6ab8963185 <unknown>\n#17 0x5a6ab897b492 <unknown>\n#18 0x5a6ab89482ef <unknown>\n#19 0x5a6ab899ae88 <unknown>\n#20 0x5a6ab899b053 <unknown>\n#21 0x5a6ab89aaddc <unknown>\n#22 0x703acbc94ac3 <unknown>\n\n", "trace": "  File \"/home/test/Desktop/sprint_7/venv/lib/python3.10/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/home/test/Desktop/sprint_7/pages/main_page.py\", line 26, in click_orders_feed_button\n    self.click_to_element(MainPageLocators.ORDERS_FEED_BUTTON)\n  File \"/home/test/Desktop/sprint_7/pages/base_page.py\", line 25, in click_to_element\n    element.click()\n  File \"/home/test/Desktop/sprint_7/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py\", line 93, in click\n    self._execute(Command.CLICK_ELEMENT)\n  File \"/home/test/Desktop/sprint_7/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py\", line 394, in _execute\n    return self._parent.execute(command, params)\n  File \"/home/test/Desktop/sprint_7/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"/home/test/Desktop/sprint_7/venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1728420161707, "stop": 1728420167430}], "start": 1728420161706, "stop": 1728420167432, "uuid": "a167167f-50a1-4729-92d3-46595ca90714", "testCaseId": "9eb91751f218a2be02a0e0981b537328", "fullName": "tests.test_feed_page.TestFeedPage#test_count_today"}