{"uuid": "5338df10-de3a-4bee-a92b-fe42faf7763e", "children": ["c8f7d1ff-ebdb-4829-89d2-2182658d7991"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "NameError: name 'Urls' is not defined\n", "trace": "  File \"/home/test/Desktop/sprint_7/venv/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/test/Desktop/sprint_7/venv/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/test/Desktop/sprint_7/venv/lib/python3.10/site-packages/_pytest/fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/home/test/Desktop/sprint_7/conftest.py\", line 34, in driver\n    driver.get(Urls.main_page)\n"}, "start": 1728420515540, "stop": 1728420518162}], "start": 1728420515540, "stop": 1728420518173}