{"uuid": "989d27f0-1b78-41cc-92f0-8c93d19aa500", "children": ["f8e74716-4376-47b0-9b53-e9cc5266a08f"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "NameError: name 'Urls' is not defined\n", "trace": "  File \"/home/test/Desktop/sprint_7/venv/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/test/Desktop/sprint_7/venv/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/test/Desktop/sprint_7/venv/lib/python3.10/site-packages/_pytest/fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/home/test/Desktop/sprint_7/conftest.py\", line 34, in driver\n    driver.get(Urls.main_page)\n"}, "start": 1728420518176, "stop": 1728420521586}], "start": 1728420518176, "stop": 1728420521716}