{"uuid": "38cd6a5f-221a-47c5-9dbb-aff36d594f2e", "children": ["9b3c3c80-a4c1-4055-ba66-8c9e12724f79"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "NameError: name 'Urls' is not defined\n", "trace": "  File \"/home/test/Desktop/sprint_7/venv/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/test/Desktop/sprint_7/venv/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/test/Desktop/sprint_7/venv/lib/python3.10/site-packages/_pytest/fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/home/test/Desktop/sprint_7/conftest.py\", line 34, in driver\n    driver.get(Urls.main_page)\n"}, "start": 1728420521720, "stop": 1728420524249}], "start": 1728420521720, "stop": 1728420524260}