{"uuid": "23723b1b-46e7-409a-9802-4cac1bdfc023", "children": ["7a44d027-6176-4206-977d-6030a39d0f47"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "NameError: name 'Urls' is not defined\n", "trace": "  File \"/home/test/Desktop/sprint_7/venv/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/test/Desktop/sprint_7/venv/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/test/Desktop/sprint_7/venv/lib/python3.10/site-packages/_pytest/fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/home/test/Desktop/sprint_7/conftest.py\", line 34, in driver\n    driver.get(Urls.main_page)\n"}, "start": 1728420510405, "stop": 1728420515403}], "start": 1728420510405, "stop": 1728420515536}